name: Question
description: Ask a question about using or contributing to this project
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
