# AI Agent Coordinator Configuration
# Version: 1.0.0
# Last Updated: 2025-10-28

# This file defines the orchestration rules for AI agents working on the
# System Governance Framework repository.

---
version: "1.0"

# Global Settings
settings:
  # Enable/disable agent orchestration
  enabled: true
  
  # Maximum concurrent agents
  max_concurrent_agents: 3
  
  # Default priority for unassigned tasks
  default_priority: medium
  
  # Require validation before merge
  require_validation: true
  
  # Handoff timeout (hours)
  handoff_timeout: 24
  
  # Enable conflict detection
  conflict_detection: true

# Agent Definitions
agents:
  coordinator:
    type: orchestrator
    capabilities:
      - task_assignment
      - conflict_resolution
      - progress_monitoring
      - resource_allocation
    authority_level: high
    
  documentation_agent:
    type: specialist
    capabilities:
      - markdown_editing
      - technical_writing
      - link_validation
      - structure_improvement
    domains:
      - "*.md"
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/PULL_REQUEST_TEMPLATE.md"
    authority_level: medium
    
  security_agent:
    type: specialist
    capabilities:
      - security_analysis
      - vulnerability_detection
      - policy_enforcement
      - compliance_checking
    domains:
      - ".github/workflows/security*.yml"
      - ".github/workflows/codeql*.yml"
      - ".github/SECURITY.md"
      - "security/*"
    authority_level: high
    
  quality_agent:
    type: specialist
    capabilities:
      - code_review
      - linting
      - testing
      - standards_enforcement
    domains:
      - ".github/workflows/ci.yml"
      - ".github/workflows/super-linter.yml"
      - ".pre-commit-config.yaml"
      - "tests/*"
    authority_level: medium
    
  community_agent:
    type: specialist
    capabilities:
      - issue_triage
      - pr_review
      - community_engagement
      - support
    domains:
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/PULL_REQUEST_TEMPLATE.md"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
    authority_level: medium
    
  validator_agent:
    type: validator
    capabilities:
      - consistency_check
      - completeness_verification
      - cross_reference_validation
      - final_approval
    domains:
      - "*"  # Can validate all domains
    authority_level: high

# Task Routing Rules
routing_rules:
  documentation_updates:
    pattern: "*.md"
    primary_agent: documentation_agent
    requires_validation: true
    validator: validator_agent
    
  security_changes:
    pattern:
      - ".github/workflows/*security*.yml"
      - ".github/workflows/*codeql*.yml"
      - ".github/SECURITY.md"
    primary_agent: security_agent
    requires_validation: true
    requires_human_review: true
    validator: validator_agent
    
  workflow_modifications:
    pattern: ".github/workflows/*.yml"
    primary_agent: quality_agent
    requires_validation: true
    validator: validator_agent
    
  community_files:
    pattern:
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/PULL_REQUEST_TEMPLATE.md"
    primary_agent: community_agent
    requires_validation: true
    requires_human_review: true
    validator: validator_agent
    
  configuration_files:
    pattern:
      - ".pre-commit-config.yaml"
      - ".gitignore"
      - "*.yml"
      - "*.yaml"
      - "*.json"
    primary_agent: quality_agent
    requires_validation: true
    validator: validator_agent

# Collaboration Rules
collaboration:
  # Tasks that require multiple agents
  multi_agent_tasks:
    - name: "comprehensive_security_review"
      agents: [security_agent, quality_agent]
      coordination: sequential
      
    - name: "major_documentation_overhaul"
      agents: [documentation_agent, community_agent]
      coordination: parallel
      
    - name: "framework_release"
      agents: [documentation_agent, quality_agent, security_agent]
      coordination: sequential
      validator: validator_agent

  # Handoff protocols
  handoff_protocols:
    standard:
      requires:
        - complete_context_summary
        - validation_checklist
        - change_documentation
      timeout: 24h
      
    emergency:
      requires:
        - critical_context_only
        - immediate_action_items
      timeout: 2h
      
    specialized:
      requires:
        - domain_specific_context
        - technical_details
        - dependency_map
      timeout: 48h

# Quality Gates
quality_gates:
  pre_handoff:
    - name: "documentation_updated"
      required: true
      
    - name: "tests_passing"
      required: true
      
    - name: "no_security_issues"
      required: true
      severity: high
      
    - name: "style_compliant"
      required: false  # Warning only
      
  post_handoff:
    - name: "context_validated"
      required: true
      
    - name: "changes_reviewed"
      required: true
      
    - name: "handoff_complete"
      required: true

# Validation Requirements
validation:
  automatic:
    - markdown_lint
    - link_check
    - yaml_syntax
    - json_syntax
    
  manual:
    - security_changes
    - community_guidelines
    - major_architecture_changes
    
  criteria:
    completeness:
      weight: 30
      min_score: 8.0
      
    correctness:
      weight: 40
      min_score: 9.0
      
    consistency:
      weight: 20
      min_score: 8.5
      
    clarity:
      weight: 10
      min_score: 7.5

# Conflict Resolution
conflict_resolution:
  strategy: human_escalation
  
  detection:
    - concurrent_edits
    - contradictory_changes
    - policy_violations
    
  escalation_path:
    - level_1: coordinator_agent
      timeout: 1h
      
    - level_2: human_maintainer
      timeout: 24h
      
    - level_3: project_lead
      timeout: 48h
      
  notification:
    - github_issue
    - email_alert

# Monitoring & Logging
monitoring:
  enabled: true
  
  metrics:
    - task_completion_rate
    - handoff_success_rate
    - average_completion_time
    - quality_score
    - conflict_rate
    
  logging:
    level: info
    format: structured
    destination: .github/agents/logs/
    
  alerts:
    - condition: "handoff_timeout_exceeded"
      action: notify_human
      
    - condition: "quality_gate_failed"
      action: block_and_notify
      
    - condition: "conflict_detected"
      action: pause_and_escalate

# Emergency Procedures
emergency:
  triggers:
    - security_vulnerability_detected
    - data_breach
    - system_outage
    - critical_bug
    
  protocol:
    - pause_all_agents
    - notify_human_immediately
    - activate_emergency_handoff
    - escalate_to_project_lead
    
  recovery:
    - assess_impact
    - implement_fix
    - validate_resolution
    - resume_normal_operations
    - post_mortem_review

# Integration Points
integrations:
  github_actions:
    enabled: true
    trigger_on:
      - pull_request
      - push
      - issue_comment
      
  pre_commit:
    enabled: true
    enforce_standards: true
    
  security_scanners:
    enabled: true
    block_on_high_severity: true

# Maintenance
maintenance:
  review_frequency: monthly
  update_frequency: quarterly
  
  responsibilities:
    - review_agent_performance
    - adjust_routing_rules
    - update_task_templates
    - refine_quality_gates
    - optimize_collaboration_patterns
